<?php

return [
		[
			'slug'    => 'reci-demo-course-rural-equity',
			'title'   => 'Place, Rurality, and Who Gets Left Out: Equity Barriers in Rural Public Service',
			'sdgs'    => [ 'Reduced Inequalities', 'Sustainable Cities and Communities' ],
			'excerpt' => 'This course explores how rurality shapes access to prevention, care, benefits, and crisis response, highlighting hidden barriers like transportation, broadband, and workforce shortages.',
			'content' => 'Have you ever wondered why some Pennsylvanians struggle to access public services simply because of where they live? This course explores how rurality shapes access to prevention, care, benefits, and crisis response, highlighting hidden barriers like transportation, broadband, and workforce shortages. Through practical examples and reflection, you\'ll learn to spot these challenges and consider ways agencies can work together to improve equity. By the end, you\'ll be ready to draft a collaboration idea to help make public services more accessible for everyone, no matter where they live.',
			'topics'  => [ 'Community Action', 'Systemic Racism', 'Technology & Equity' ],
			'spheres' => [ 'Recognizing Racial Oppression', 'Gauging Racial Inequities' ],
			'tags'    => [ 'rural access', 'public service barriers', 'transportation', 'broadband equity' ],
			'image'   => 'site/learn/1.webp',
			'post_date' => '2025-09-08 00:09:28',
			'meta'    => [
				'_reci_course_level'          => 'beginner',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/wmRbFYReCPUHZc9hWcObZ',
				'_reci_course_lessons'        => wp_json_encode([
					'Opening: Why Place Matters in Public Service Access',
					'How Rurality Changes Access: A Closer Look',
					'Hidden Barriers: What Gets in the Way?',
					'Action Planning: Collaborating for Rural Equity'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-structural-racism',
			'title'   => 'Race and Structural Racism in Pennsylvania Systems',
			'sdgs'    => [ 'Reduced Inequalities', 'Peace, Justice and Strong Institutions' ],
			'excerpt' => 'Explore how structural racism operates across Pennsylvania systems and how policies can create unequal outcomes.',
			'content' => 'Have you ever wondered why some Pennsylvanians struggle to access public services simply because of where they live? This course explores how rurality shapes access to prevention, care, benefits, and crisis response, highlighting hidden barriers like transportation, broadband, and workforce shortages. Through practical examples and reflection, you\'ll learn to spot these challenges and consider ways agencies can work together to improve equity. By the end, you\'ll be ready to draft a collaboration idea to help make public services more accessible for everyone, no matter where they live.',
			'topics'  => [ 'Systemic Racism', 'Community Action' ],
			'spheres' => [ 'Recognizing Racial Oppression' ],
			'tags'    => [ 'structural racism', 'Pennsylvania systems', 'policy equity', 'racial justice' ],
			'image'   => 'site/learn/2.webp',
			'post_date' => '2025-01-06 03:26:36',
			'meta'    => [
				'_reci_course_level'          => 'beginner',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/wmRbFYReCPUHZc9hWcObZ',
				'_reci_course_lessons'        => wp_json_encode([
					'Understanding Bias and Structural Racism',
					'How Policies and Programs Create Unequal Outcomes',
					'Practical Equity Adjustments in Agency Processes',
					'Action Planning and Next Steps'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-health-behaviors',
			'title'   => 'Health Behaviors in Context: Beyond Personal Choice',
			'sdgs'    => [ 'Good Health and Well-being', 'Reduced Inequalities' ],
			'excerpt' => 'Learn how health behaviors are shaped by stress, trauma, environments, and policies rather than just personal decisions.',
			'content' => 'Have you ever wondered why healthy choices are not always easy or available? In this course, you will learn how health behaviors are shaped by more than just personal decisions. We will explore how stress, trauma, environments, and policies influence what options people have, and how you can design programs that support rather than judge. By the end, you will be equipped to create practical, non-stigmatizing solutions that help communities overcome barriers to better health.',
			'topics'  => [ 'Health Disparities' ],
			'spheres' => [ 'Gauging Racial Inequities' ],
			'tags'    => [ 'health behavior', 'behavioral determinants', 'program design', 'non-stigmatizing' ],
			'image'   => 'site/learn/3.webp',
			'post_date' => '2026-03-09 01:22:04',
			'meta'    => [
				'_reci_course_level'          => 'intermediate',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/Zk2IXlHRqHCxBBloeKHVl',
				'_reci_course_lessons'        => wp_json_encode([
					'Understanding Behavioral Determinants',
					'Stress, Trauma, and Scarcity: Impacts on Behavior',
					'Environments, Policies, and Health Behavior Options',
					'Supportive, Non-Stigmatizing Program Design and Action Planning'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-religious-respect',
			'title'   => 'Religion, Respect, and Equitable Service Delivery',
			'sdgs'    => [ 'Reduced Inequalities', 'Peace, Justice and Strong Institutions' ],
			'excerpt' => 'Learn how to prevent religious bias in agency systems and support inclusive service delivery.',
			'content' => 'Have you ever wondered how small details in public service can unintentionally exclude people of faith? In this course, you will learn how religious bias can show up in agency systems and what you can do to prevent it. You will practice using a minimum harm checklist to make your forms, policies, and communications more inclusive. You will also explore when working with faith leaders can help your agency build trust and better serve Pennsylvania\'s diverse communities. By the end, you will have practical tools and an action plan to support respectful, equitable service delivery.',
			'topics'  => [ 'Cultural Identity', 'Systemic Racism', 'Community Action' ],
			'spheres' => [ 'Embracing Racial Diversity', 'Gauging Racial Inequities' ],
			'tags'    => [ 'religious respect', 'faith inclusion', 'minimum harm', 'inclusive service' ],
			'image'   => 'site/learn/4.webp',
			'post_date' => '2026-02-08 00:03:57',
			'meta'    => [
				'_reci_course_level'          => 'beginner',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/gpSf4aNZgEwXF9vUIGv7M',
				'_reci_course_lessons'        => wp_json_encode([
					'Opening: Why Religious Respect Matters in Public Service',
					'Recognizing Religious Bias in Systems: Common Pitfalls and Realities',
					'Applying the Minimum Harm Checklist: Forms, Policies, and Communications',
					'Partnering with Faith Leaders and Action Planning'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-biology-genetics',
			'title'   => 'Biology, Genetics, and What Not to Assume',
			'sdgs'    => [ 'Good Health and Well-being', 'Quality Education' ],
			'excerpt' => 'Learn how biology and genetics influence health while exploring the role of social and structural factors.',
			'content' => 'Have you ever wondered how much biology and genetics really shape health—and what assumptions to avoid? In this course, you’ll learn how biology and genetics influence health risk and response, while also exploring the powerful role of social and structural factors. You’ll discover why race is not a reliable substitute for genetics in public health, and practice responsible ways to interpret health data. Through practical examples, interactive activities, and action planning, you’ll gain the skills to use biological information thoughtfully in your program planning and public health work.',
			'topics'  => [ 'Health Disparities', 'Education' ],
			'spheres' => [ 'Gauging Racial Inequities' ],
			'tags'    => [ 'genetics and health', 'race and genetics', 'responsible data', 'health equity' ],
			'image'   => 'site/learn/5.webp',
			'post_date' => '2024-03-29 16:44:20',
			'meta'    => [
				'_reci_course_level'          => 'intermediate',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/BZ12gzkZvifIQWjwz-e-m',
				'_reci_course_lessons'        => wp_json_encode([
					'Biology and Genetics: What Shapes Health?',
					'Beyond Biology: Social and Structural Drivers of Health Inequities',
					'Why Race Is Not a Stand-In for Genetics',
					'Applying What You Know: Responsible Data Use and Program Planning'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-work-conditions',
			'title'   => 'Work, Working Conditions, and Health',
			'sdgs'    => [ 'Good Health and Well-being', 'Decent Work and Economic Growth' ],
			'excerpt' => 'Explore how job quality and workplace environments affect health and wellbeing.',
			'content' => 'How do your daily work conditions shape your health and wellbeing? In this course, you\'ll explore the practical ways that job quality and workplace environments affect health, from wages and schedules to safety and stress. You\'ll learn to recognize occupational risks, understand how inequities influence who faces higher risks, and discover actionable steps agencies can take to create safer, healthier workplaces. Through real-world examples, reflection, and action planning, you\'ll gain tools to make a positive impact across Pennsylvania Commonwealth agencies.',
			'topics'  => [ 'Workplace Equity', 'Health Disparities' ],
			'spheres' => [ 'Gauging Racial Inequities' ],
			'tags'    => [ 'working conditions', 'occupational health', 'workplace safety', 'job quality' ],
			'image'   => 'site/learn/6.webp',
			'post_date' => '2026-05-10 01:01:45',
			'meta'    => [
				'_reci_course_level'          => 'beginner',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/XAwcEi4rgWHl34xbda-7v',
				'_reci_course_lessons'        => wp_json_encode([
					'How Work Shapes Health and Wellbeing',
					'Recognizing Occupational Risks in the Workplace',
					'Understanding Inequities in Workplace Health Risks',
					'Taking Action: Agency Roles and Collaboration for Safer Workplaces'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-healthcare-access',
			'title'   => 'Access, Quality, and Trust in Health Care',
			'sdgs'    => [ 'Good Health and Well-being', 'Reduced Inequalities' ],
			'excerpt' => 'Explore the barriers that affect fair health care access in Pennsylvania.',
			'content' => 'What stands in the way of fair health care access? In this course, you will explore the real barriers that affect how people in Pennsylvania get the care they need. You will learn how system-level issues, quality and safety concerns, and trust all shape health outcomes, and discover practical ways to use an equity lens in your daily work. Through real-life examples, reflection, and action planning, you will gain tools to help improve access and quality for everyone.',
			'topics'  => [ 'Technology & Equity', 'Health Disparities', 'Community Action' ],
			'spheres' => [ 'Gauging Racial Inequities' ],
			'tags'    => [ 'healthcare access', 'quality of care', 'trust', 'equity lens' ],
			'image'   => 'site/learn/7.webp',
			'post_date' => '2026-02-12 12:57:20',
			'meta'    => [
				'_reci_course_level'          => 'intermediate',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/ZcHH6Pk7jrx_2G-uSR89n',
				'_reci_course_lessons'        => wp_json_encode([
					'Understanding System-Level Barriers to Health Care Access',
					'Quality and Safety: Impact on Different Groups',
					'Trust, Prior Harm, and Care Seeking',
					'Applying an Equity Lens: Referral Pathways and Measurement'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-sdoh-action',
			'title'   => 'Social Determinants of Health: Turning Concepts Into Action',
			'sdgs'    => [ 'Good Health and Well-being', 'No Poverty', 'Reduced Inequalities' ],
			'excerpt' => 'Learn how everyday agency processes affect health outcomes and how to reduce disparities.',
			'content' => 'How do everyday agency processes affect health outcomes in Pennsylvania? In this course, you will learn what social determinants of health (SDOH) are, why they matter, and how they connect to identity-based barriers. Through practical examples, a case scenario, and reflection, you will learn to spot barriers, apply an administrative burden lens, and plan changes to reduce disparities. By the end, you will be ready to take concrete steps to make your agency\'s work more equitable and effective.',
			'topics'  => [ 'Health Disparities', 'Community Action', 'Cultural Identity' ],
			'spheres' => [ 'Gauging Racial Inequities' ],
			'tags'    => [ 'social determinants', 'administrative burden', 'equity action', 'disparities' ],
			'image'   => 'site/learn/8.webp',
			'post_date' => '2024-03-19 03:52:28',
			'meta'    => [
				'_reci_course_level'          => 'intermediate',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/RxUe6oYyQiWOVvW-DGfVL',
				'_reci_course_lessons'        => wp_json_encode([
					'Understanding Social Determinants of Health (SDOH)',
					'SDOH and Identity: Understanding Unequal Outcomes',
					'Spotting Barriers and Reducing Administrative Burden',
					'Measuring Change and Planning for Action'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-disability-access',
			'title'   => 'Disability, Accessibility, and Ableism in Public Systems',
			'sdgs'    => [ 'Reduced Inequalities', 'Peace, Justice and Strong Institutions' ],
			'excerpt' => 'Learn why accessibility is an equity issue and gain tools to make your work more inclusive.',
			'content' => 'Have you ever wondered how small changes can make public services more accessible for everyone? In this course, you will learn why accessibility is an equity issue and not just an extra feature. You will discover common barriers in physical, digital, and communication spaces, and gain practical tools to make your work more inclusive. By the end, you will be ready to create a simple, effective plan to improve accessibility in your agency\'s activities.',
			'topics'  => [ 'Technology & Equity', 'Cultural Identity', 'Community Action' ],
			'spheres' => [ 'Embracing Racial Diversity', 'Gauging Racial Inequities' ],
			'tags'    => [ 'accessibility', 'ableism', 'inclusive design', 'disability equity' ],
			'image'   => 'site/learn/9.webp',
			'post_date' => '2025-01-27 01:22:27',
			'meta'    => [
				'_reci_course_level'          => 'beginner',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/5hppFtt0v-Q81SYiXZslq',
				'_reci_course_lessons'        => wp_json_encode([
					'Why Accessibility Matters: Equity in Public Services',
					'Spotting Access Barriers: Physical, Digital, and Communication Challenges',
					'Making Content Accessible: Practical Steps for Inclusive Learning',
					'Planning for Change: Your Accessibility Action Plan'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-lgbtq-practice',
			'title'   => 'Gender Identity and Sexual Orientation in Policy and Practice',
			'sdgs'    => [ 'Gender Equality', 'Reduced Inequalities' ],
			'excerpt' => 'Learn to recognize and reduce administrative obstacles for LGBTQ+ residents and staff.',
			'content' => 'Have you ever wondered how agency forms or policies might unintentionally create barriers for LGBTQ+ residents or staff? In this course, you will learn to recognize common administrative obstacles, apply practical privacy safeguards, and develop an action plan for more inclusive practices. Through real-world examples and reflection, you will gain tools to make your agency\'s processes safer and more welcoming. By the end, you will be ready to identify barriers and take concrete steps toward positive change.',
			'topics'  => [ 'Cultural Identity', 'Community Action' ],
			'spheres' => [ 'Embracing Racial Diversity', 'Gauging Racial Inequities' ],
			'tags'    => [ 'LGBTQ+ inclusion', 'gender identity', 'privacy', 'inclusive policy' ],
			'image'   => 'site/learn/10.webp',
			'post_date' => '2025-09-12 20:54:57',
			'meta'    => [
				'_reci_course_level'          => 'beginner',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/dY3vp-l2SUkzWT88ddF_5',
				'_reci_course_lessons'        => wp_json_encode([
					'Understanding Administrative Barriers for LGBTQ+ Individuals',
					'Safeguarding Privacy When Collecting Sensitive Identity Data',
					'Inclusive Practices: Quick Fixes for Agency Units and Programs',
					'Action Planning and Knowledge Check'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-economic-stability',
			'title'   => 'Economic Stability as a Cross-Cutting Barrier',
			'sdgs'    => [ 'No Poverty', 'Decent Work and Economic Growth' ],
			'excerpt' => 'Understand how economic costs like fees and transportation create barriers for Pennsylvanians.',
			'content' => 'Have you ever wondered why some people struggle to access public services, even when help is available? This course will help you understand how economic costs—like fees, fines, paperwork, and transportation—can create real barriers for Pennsylvanians. Through practical examples, a case scenario, and hands-on activities, you\'ll learn to spot and reduce these barriers in your agency\'s processes while keeping programs accountable. By the end, you\'ll be ready to make meaningful, low cost changes that improve access for everyone.',
			'topics'  => [ 'Workplace Equity', 'Technology & Equity', 'Community Action' ],
			'spheres' => [ 'Gauging Racial Inequities' ],
			'tags'    => [ 'economic stability', 'administrative burden', 'fees and fines', 'barrier reduction' ],
			'image'   => 'site/learn/11.webp',
			'post_date' => '2026-04-27 05:04:38',
			'meta'    => [
				'_reci_course_level'          => 'intermediate',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/SLd4W3xGGIfmlio2gOItR',
				'_reci_course_lessons'        => wp_json_encode([
					'Understanding Economic Barriers in Public Service',
					'Spotting Administrative Burdens in Agency Processes',
					'Reducing Barriers While Maintaining Accountability',
					'Action Planning: Applying What You\'ve Learned'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-cross-culture',
			'title'   => 'Working Across Cultures: Practical Skills for Inclusive Service Delivery',
			'sdgs'    => [ 'Reduced Inequalities', 'Peace, Justice and Strong Institutions' ],
			'excerpt' => 'Learn practical skills to serve Pennsylvania\'s diverse communities with dignity and respect.',
			'content' => 'Have you ever wondered why a simple service interaction can feel so different for people from various backgrounds? In this course, you will learn practical skills to serve Pennsylvania\'s diverse communities with dignity and respect. Through real-world examples, reflection, and action planning, you will discover how culture shapes trust and communication, spot and reduce unintentional barriers, use inclusive communication practices, and build lasting trust with the people you serve. By the end, you will be ready to apply what you\'ve learned to make your services more welcoming and effective for everyone.',
			'topics'  => [ 'Systemic Racism', 'Cultural Identity', 'Community Action' ],
			'spheres' => [ 'Embracing Racial Diversity' ],
			'tags'    => [ 'cross-cultural', 'culturally responsive', 'community trust', 'inclusive service' ],
			'image'   => 'site/learn/12.webp',
			'post_date' => '2025-01-18 08:06:11',
			'meta'    => [
				'_reci_course_level'          => 'beginner',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/IK9-nahUGZvXktiOvvIJB',
				'_reci_course_lessons'        => wp_json_encode([
					'How Culture Shapes Trust and Service Use',
					'Spotting and Reducing Unintentional Barriers',
					'Culturally Responsive Communication in Practice',
					'Building Trust and Planning for Inclusive Engagement'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-immigration',
			'title'   => 'Immigration, Documentation Concerns, and Safe Access',
			'sdgs'    => [ 'Reduced Inequalities', 'Peace, Justice and Strong Institutions' ],
			'excerpt' => 'Explore how fear and misinformation about immigration can prevent people from accessing help.',
			'content' => 'Have you ever wondered why some eligible residents hesitate to use public services? This course explores how fears and misinformation about immigration and documentation can prevent people from accessing the help they need. You will learn to spot common barriers, communicate more clearly to reduce unnecessary fear, and connect residents with trusted resources. Through practical examples, reflection, and action planning, you will gain tools to create safer, more welcoming pathways for all.',
			'topics'  => [ 'Technology & Equity', 'Cultural Identity', 'Community Action' ],
			'spheres' => [ 'Building Racial Empathy' ],
			'tags'    => [ 'immigration', 'documentation concerns', 'safe access', 'fear reduction' ],
			'image'   => 'site/learn/13.webp',
			'post_date' => '2024-08-10 22:49:17',
			'meta'    => [
				'_reci_course_level'          => 'beginner',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/I-jvtPO41gEnL6Fx6GmeE',
				'_reci_course_lessons'        => wp_json_encode([
					'Opening: Why Safe Access Matters',
					'Spotting Barriers: Where Fear and Misinformation Disrupt Access',
					'Clear Communication: Reducing Fear in Public Messages',
					'Building Safer Pathways: Referrals, Partnerships, and Action Planning'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-learning-action',
			'title'   => 'From Learning to Action: Using Data, Tools, and Implementation Supports',
			'sdgs'    => [ 'Quality Education', 'Reduced Inequalities' ],
			'excerpt' => 'Turn equity learning into real change by using data and implementation metrics.',
			'content' => 'How do you turn equity learning into real change at work? This course gives you practical steps to move from understanding equity concepts to building and acting on a plan. You will learn how to use data to spot gaps, select meaningful metrics, create a basic equity action plan, and tackle common barriers. By the end, you will have the tools and confidence to take your next step toward equity in your agency.',
			'topics'  => [ 'Education', 'Community Action', 'Technology & Equity' ],
			'spheres' => [ 'Gauging Racial Inequities' ],
			'tags'    => [ 'equity action plan', 'implementation', 'data metrics', 'organizational change' ],
			'image'   => 'site/learn/14.webp',
			'post_date' => '2026-04-04 10:06:37',
			'meta'    => [
				'_reci_course_level'          => 'advanced',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/ShpmPC_Homrq1fQ0XLypE',
				'_reci_course_lessons'        => wp_json_encode([
					'Getting Started: Turning Equity Learning into Action',
					'Using Data to Identify Gaps and Set Metrics',
					'Building a Basic Equity Action Plan',
					'Overcoming Barriers and Planning Next Steps'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-legal-systems',
			'title'   => 'How Laws and Legal Systems Shape Health Outcomes',
			'sdgs'    => [ 'Good Health and Well-being', 'Peace, Justice and Strong Institutions' ],
			'excerpt' => 'Explore how laws, court practices, and agency rules impact health outcomes.',
			'content' => 'Have you ever wondered how a simple rule or policy can shape someone\'s health? In this course, you\'ll explore how laws, court practices, and agency rules can impact health outcomes—sometimes in ways that aren\'t obvious. You\'ll learn to spot legal barriers, use a simple equity check to flag unequal impacts, and discover when and how to connect people with legal help. By the end, you\'ll be ready to take practical steps to reduce legal harm and improve access to services in your agency.',
			'topics'  => [ 'Health Disparities', 'Community Action' ],
			'spheres' => [ 'Recognizing Racial Oppression' ],
			'tags'    => [ 'law and health', 'legal barriers', 'equity check', 'policy impact' ],
			'image'   => 'site/learn/15.webp',
			'post_date' => '2025-02-20 05:52:01',
			'meta'    => [
				'_reci_course_level'          => 'intermediate',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/78RKOjQegi61RoUXRqcUv',
				'_reci_course_lessons'        => wp_json_encode([
					'Introduction: How Laws Shape Health',
					'Spotting Legal Barriers to Services',
					'Equity Checks: Spotting Unequal Impacts',
					'Legal Help Pathways and Action Planning'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-power-decisions',
			'title'   => 'Power, Public Decisions, and Health Equity',
			'sdgs'    => [ 'Good Health and Well-being', 'Reduced Inequalities' ],
			'excerpt' => 'Learn how political power and public narratives influence health equity.',
			'content' => 'How do public decisions shape the health of our communities? In this course, you will learn how political power, agency priorities, and public narratives influence health equity in Pennsylvania. Through practical examples, a real-world case, and reflection activities, you will gain tools to build trust, communicate clearly, and foster partnerships that last. By the end, you will be ready to apply these strategies in your work to support healthier, more equitable communities.',
			'topics'  => [ 'Health Disparities', 'Community Action' ],
			'spheres' => [ 'Recognizing Racial Oppression', 'Gauging Racial Inequities' ],
			'tags'    => [ 'political power', 'health equity', 'community engagement', 'public decisions' ],
			'image'   => 'site/learn/16.webp',
			'post_date' => '2024-02-19 14:43:15',
			'meta'    => [
				'_reci_course_level'          => 'intermediate',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/UFg6TpfG7dPH6lUsdFmRT',
				'_reci_course_lessons'        => wp_json_encode([
					'Understanding Political Power and Health Outcomes',
					'Budgets, Priorities, and Service Quality',
					'Narratives, Trust, and Community Engagement',
					'Building Communication Strategies and Lasting Partnerships'
				]),
			],
		],
		[
			'slug'    => 'reci-demo-course-tech-equity',
			'title'   => 'Technology, Access, and Health Equity',
			'sdgs'    => [ 'Industry, Innovation and Infrastructure', 'Reduced Inequalities' ],
			'excerpt' => 'Learn how technology and access connect to health equity in Pennsylvania.',
			'content' => 'How do digital tools shape who can access public services and achieve better health? In this course, you will learn how technology, access, and health equity are connected, and why it matters for your work with Pennsylvania constituents. You will explore digital barriers, see how data and algorithms can create unequal impacts, and use practical tools to review and improve your own programs. By the end, you will be ready to apply a digital equity checklist and create a simple plan to help make public services fairer and more accessible for everyone.',
			'topics'  => [ 'Technology & Equity', 'Community Action' ],
			'spheres' => [ 'Gauging Racial Inequities' ],
			'tags'    => [ 'digital equity', 'digital determinants', 'algorithmic bias', 'technology access' ],
			'image'   => 'site/learn/17.webp',
			'post_date' => '2025-06-10 04:56:18',
			'meta'    => [
				'_reci_course_level'          => 'beginner',
				'_reci_course_enrollment_url' => 'https://share.articulate.com/UqDHKQcCojlYjkzGPuljA',
				'_reci_course_lessons'        => wp_json_encode([
					'Digital Determinants of Health: What They Are and Why They Matter',
					'Identifying Digital Barriers in Public Services',
					'Algorithms, Data Gaps, and Unequal Impacts',
					'Applying Digital Equity: Checklist and Action Planning'
				]),
			],
		],
	];
