<?php

return [
		[
			'slug'    => 'reci-demo-event-cohort-session-14',
			'title'   => 'RECI Fall Cohort — Session 14: Gauging Racial Inequities',
			'excerpt' => 'Explore frameworks for measuring racial inequities and championing racial justice in this penultimate session of the RECI Virtual Fall Cohort.',
			'content' => reci_demo_lorem( 2 ),
			'topics'  => [ 'Systemic Racism', 'Workplace Equity' ],
			'image'   => 'site/events/national-day-racial-healing.webp',
			'post_date' => '2026-06-04 11:30:00',
			'meta'    => [
			'_reci_event_start_date'       => '2026-11-04',
			'_reci_event_end_date'         => '2026-11-04',
			'_reci_event_start_time'       => '11:30 AM',
			'_reci_event_end_time'         => '1:00 PM',
			'_reci_event_timezone'         => 'EST',
			'_reci_event_is_virtual'       => '1',
			'_reci_event_location_name'    => 'Virtual — Zoom',
			'_reci_event_registration_url' => '',
			'_reci_event_cta_label'        => 'Learn More',
		],
	],
	[
		'slug'    => 'reci-demo-event-cohort-closing',
		'title'   => 'RECI Fall Cohort — Closing Session',
		'excerpt' => 'Join us for the final session of the RECI Virtual Fall Cohort as we reflect on our journey and celebrate participant achievements.',
		'content' => reci_demo_lorem( 2 ),
		'topics'  => [ 'Community Action', 'Intersectionality' ],
		'image'   => 'site/events/reci-cohort-closing.webp',
		'post_date' => '2026-06-11 11:30:00',
		'meta'    => [
			'_reci_event_start_date'       => '2026-11-11',
			'_reci_event_end_date'         => '2026-11-11',
			'_reci_event_start_time'       => '11:30 AM',
			'_reci_event_end_time'         => '1:00 PM',
			'_reci_event_timezone'         => 'EST',
			'_reci_event_is_virtual'       => '1',
			'_reci_event_location_name'    => 'Virtual — Zoom',
			'_reci_event_registration_url' => '',
			'_reci_event_cta_label'        => 'Learn More',
		],
	],
	[
		'slug'    => 'reci-demo-event-racial-healing',
		'title'   => 'National Day of Racial Healing',
		'excerpt' => 'A meaningful gathering in recognition of the National Day of Racial Healing, featuring collective reflection and dialogue.',
		'content' => reci_demo_lorem( 2 ),
		'topics'  => [ 'Community Action', 'Cultural Identity' ],
		'image'   => 'site/events/national-day-racial-healing.webp',
		'post_date' => '2025-10-15 11:00:00',
		'meta'    => [
			'_reci_event_start_date'       => '2026-01-20',
			'_reci_event_end_date'         => '2026-01-20',
			'_reci_event_start_time'       => '11:00 AM',
			'_reci_event_end_time'         => '1:00 PM',
			'_reci_event_timezone'         => 'EST',
			'_reci_event_is_virtual'       => '0',
			'_reci_event_location_name'    => "O'Hara Student Center, Ballroom",
			'_reci_event_location_address' => "3900 O'Hara Street, Pittsburgh, PA 15260",
		],
	],
	[
		'slug'    => 'reci-demo-event-human-flourishing',
		'title'   => 'Human Flourishing Symposium',
		'excerpt' => 'A transformative symposium exploring pathways to thriving — shifting from deficit to possibility in community well-being.',
		'content' => reci_demo_lorem( 2 ),
		'topics'  => [ 'Health Disparities', 'Community Action' ],
		'image'   => 'site/events/human-flourishing-symposium.webp',
		'post_date' => '2025-11-20 09:00:00',
		'meta'    => [
			'_reci_event_start_date'       => '2026-11-23',
			'_reci_event_end_date'         => '2026-11-23',
			'_reci_event_start_time'       => '9:00 AM',
			'_reci_event_end_time'         => '3:00 PM',
			'_reci_event_timezone'         => 'EST',
			'_reci_event_is_virtual'       => '0',
			'_reci_event_location_name'    => 'Alumni Hall, Connolly Ballroom',
			'_reci_event_location_address' => '4227 Fifth Avenue, Pittsburgh, PA 15260',
		],
	],
	[
		'slug'    => 'reci-demo-event-refugee-strategies',
		'title'   => 'From Minneapolis to Pittsburgh: Supporting Refugee & Immigrant Neighbors',
		'excerpt' => 'A conversation with front-line supports and organizers on community strategies for supporting refugee and immigrant communities.',
		'content' => reci_demo_lorem( 2 ),
		'topics'  => [ 'Community Action', 'Cultural Identity' ],
		'image'   => 'site/events/minneapolis-refugee.webp',
		'post_date' => '2026-01-10 17:00:00',
		'meta'    => [
			'_reci_event_start_date'       => '2026-11-30',
			'_reci_event_end_date'         => '2026-11-30',
			'_reci_event_start_time'       => '5:00 PM',
			'_reci_event_end_time'         => '7:00 PM',
			'_reci_event_timezone'         => 'EST',
			'_reci_event_is_virtual'       => '1',
			'_reci_event_location_name'    => 'Cathedral of Learning, Room 2017',
			'_reci_event_location_address' => 'Fifth Ave at Bigelow, Pittsburgh, PA 15213',
			'_reci_event_registration_url' => 'https://pitt.co1.qualtrics.com/jfe/form/SV_difa0J2zKNg3myW',
			'_reci_event_cta_label'        => 'Watch Recording',
		],
	],
	];
