<?php

return [
		[
			'slug'    => 'healing-overflow-love-dating',
			'title'   => 'Looking for love in all the wrong places?',
			'excerpt' => 'Love panel guests share tips for healing your dating life.',
			'content' => 'Dr. Toy hosts a relationship and dating panel featuring a licensed therapist/professor (Jessica Gurley) and University of Pittsburgh college students (Jackson and Hannah). They break down the modern \'talking stage,\' \'situationships,\' identifying red flags, exploring personal childhood attachment styles, and overcoming loneliness through community.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Cultural Identity',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Cultural Identity' ],
			'spheres' => [ 'Building Racial Empathy' ],
			'sdgs'    => [ 'Reduced Inequalities' ],
			'tags'    => [ 'dating', 'healing', 'community' ],
			'image'   => 'site/podcasts/healing-overflow-1.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/Naw5tyef16w',
				'_reci_podcast_duration_label' => '1h 1m',
				'_reci_podcast_duration_secs'  => 3664,
			],
			'post_date'=> '2025-08-31 22:04:19',
		],
		[
			'slug'    => 'healing-overflow-finances',
			'title'   => 'Healing Finances Through Basic Financial Literacy',
			'excerpt' => 'Breaking generational financial trauma and shifting out of a poverty mindset.',
			'content' => 'Dr. Toy sits down with financial coach and business owner Tyler Culverson in her new studio. They unpack the realities of breaking generational financial trauma, shifting out of a \'poverty mindset,\' the critical steps to starting an achievable budget, understanding credit card utilization, and how to use basic banking tools (like high-yield accounts and CDs) to build personal leverage.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Workplace Equity',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Workplace Equity', 'Technology & Equity' ],
			'spheres' => [ 'Gauging Racial Inequities' ],
			'sdgs'    => [ 'No Poverty' ],
			'tags'    => [ 'finances', 'generational trauma', 'budgeting' ],
			'image'   => 'site/podcasts/healing-overflow-2.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/owr84NiBzkM',
				'_reci_podcast_duration_label' => '1h 9m',
				'_reci_podcast_duration_secs'  => 4157,
			],
			'post_date'=> '2024-12-04 08:30:33',
		],
		[
			'slug'    => 'healing-overflow-health-wellness',
			'title'   => 'Healing on the Health and Wellness Journey',
			'sdgs'    => [ 'Good Health and Well-being' ],
			'excerpt' => 'The science of stress, cortisol, and sustainable wellness adjustments.',
			'content' => 'Dr. Toy interviews exercise physiologist, nutritionist, and wellness coach Dr. Camille Clark Smith (founder of THAW). Dr. Camille shares her personal journey of transitioning from Jamaica and overcoming obesity (reaching 280 lbs). The episode dives into the science of stress and cortisol, emotional eating, and why tiny, sustainable adjustments like strength training, hydration, and a 2-hour pre-bedtime fasting window beat extreme fad diets.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Health Disparities',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Health Disparities', 'Cultural Identity' ],
			'spheres' => [ 'Gauging Racial Inequities' ],
			'tags'    => [ 'wellness', 'stress', 'cortisol' ],
			'image'   => 'site/podcasts/healing-overflow-3.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/IgWVHno-Vxw',
				'_reci_podcast_duration_label' => '50m',
				'_reci_podcast_duration_secs'  => 3006,
			],
			'post_date'=> '2025-11-06 13:51:31',
		],
		[
			'slug'    => 'healing-overflow-news-blues',
			'title'   => 'How to Avoid the News Blues!',
			'sdgs'    => [ 'Good Health and Well-being' ],
			'excerpt' => 'Tackling news anxiety and doom-scrolling to protect your nervous system.',
			'content' => 'A solo episode where Dr. Toy tackles \'news anxiety\' and doom-scrolling. She explains how constant exposure to negative media overloads our autonomic nervous system and triggers a chronic fight-or-flight state. She provides practical coping strategies, a guide on running a \'news diet,\' and structural tips on how parents can talk to children about terrifying current events without amplifying their fear.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Cultural Identity',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Cultural Identity' ],
			'spheres' => [ 'Building Racial Empathy' ],
			'tags'    => [ 'news anxiety', 'doomscrolling', 'mental health' ],
			'image'   => 'site/podcasts/healing-overflow-4.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/-XIk9ZDZdwA',
				'_reci_podcast_duration_label' => '35m',
				'_reci_podcast_duration_secs'  => 2114,
			],
			'post_date'=> '2025-09-22 17:50:37',
		],
		[
			'slug'    => 'healing-overflow-social-worker',
			'title'   => 'What a social worker really is and what it really isn’t',
			'sdgs'    => [ 'Decent Work and Economic Growth', 'Reduced Inequalities' ],
			'excerpt' => 'Debunking myths about social work and exploring professional identity.',
			'content' => 'Dr. Toy welcomes her friend and MSW program director, Dr. Yodit Betru, to discuss her book Becoming a Social Worker For Dummies. Dr. Yodit shares her origin story as a political refugee from Ethiopia and addresses massive myths about the profession—such as the \'vow of poverty\' and child removal fearsL They explore the flexibility of social work versus psychology, specialized niche opportunities, and macro-level interventions.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Community Action',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Education', 'Community Action' ],
			'spheres' => [ 'Recognizing Racial Oppression' ],
			'tags'    => [ 'social work', 'refugees', 'professional identity' ],
			'image'   => 'site/podcasts/healing-overflow-5.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/OXwp6xwkG0w',
				'_reci_podcast_duration_label' => '54m',
				'_reci_podcast_duration_secs'  => 3299,
			],
			'post_date'=> '2025-01-20 19:22:47',
		],
		[
			'slug'    => 'healing-overflow-compassion-fatigue',
			'title'   => 'Building Immunity to Compassion Fatigue',
			'sdgs'    => [ 'Good Health and Well-being', 'Decent Work and Economic Growth' ],
			'excerpt' => 'Mapping the compassion stress cycle and avoiding burnout in caregiving.',
			'content' => 'Dr. Toy interviews evidence-based compassion fatigue expert Sharice Nance, LCSW. Sharice openly shares her early failure with the licensing exam and how she pushed past testing anxiety to build a thriving private practice. She maps out the \'compassion stress cycle\'—tracing the stages from secondary trauma and vicarious trauma down to compassion fatigue and full burnout. They discuss individual self-soothing, systemic capacity building, and organizational responsibility.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Workplace Equity',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Workplace Equity', 'Health Disparities' ],
			'spheres' => [ 'Building Racial Empathy' ],
			'tags'    => [ 'compassion fatigue', 'burnout', 'self-care' ],
			'image'   => 'site/podcasts/healing-overflow-6.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/WRcaQlBYuQ0',
				'_reci_podcast_duration_label' => '52m',
				'_reci_podcast_duration_secs'  => 3129,
			],
			'post_date'=> '2024-01-13 08:14:49',
		],
		[
			'slug'    => 'healing-overflow-breakup-music',
			'title'   => 'Finding Happiness and Healing After a Breakup Through Music and Journaling',
			'sdgs'    => [ 'Good Health and Well-being' ],
			'excerpt' => 'Using music and guided journaling to unpack emotional baggage.',
			'content' => 'Dr. Toy sits down with a creative University of Pittsburgh student, Zora Borde-Perry, author of the music-guided journal Reflections in Rhythm. Zora explains how she self-published her work via Amazon KDP in just over two weeks following a painful 5-year breakup. They break down the therapeutic benefits of analyzing songs like Reason by Omah Lay, Bag Lady by Erykah Badu, and Cranes in the Sky by Solange to safely unpack emotional baggage.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Cultural Identity',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Cultural Identity' ],
			'spheres' => [ 'Building Racial Empathy' ],
			'tags'    => [ 'breakups', 'music therapy', 'journaling' ],
			'image'   => 'site/podcasts/healing-overflow-7.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/Fq4bw_I4yPg',
				'_reci_podcast_duration_label' => '38m',
				'_reci_podcast_duration_secs'  => 2293,
			],
			'post_date'=> '2025-07-15 10:27:34',
		],
		[
			'slug'    => 'healing-overflow-autism',
			'title'   => 'Autism Spectrum Disorder (ASD) is Explored Through a Mother\'s Eyes',
			'sdgs'    => [ 'Good Health and Well-being', 'Reduced Inequalities' ],
			'excerpt' => 'A transparent look at raising a child with ASD and navigating the IEP system.',
			'content' => 'Dr. Toy interviews AJ Jefferson, the CEO of the Homeless Children\'s Education Fund. AJ shares a deeply moving, transparent look at her personal 19-year journey raising her son, Caleb, who is diagnosed with Autism Spectrum Disorder (ASD). She opens up about the initial heartbreak and parental guilt upon diagnosis, navigating the public school IEP (Individualized Education Program) system across different states, and the power of letting your child unapologetically be who they are.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Education',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Health Disparities', 'Education' ],
			'spheres' => [ 'Embracing Racial Diversity' ],
			'tags'    => [ 'autism', 'ASD', 'parenting', 'IEP' ],
			'image'   => 'site/podcasts/healing-overflow-8.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/VTKhSp1J6zE',
				'_reci_podcast_duration_label' => '39m',
				'_reci_podcast_duration_secs'  => 2350,
			],
			'post_date'=> '2024-05-27 00:27:35',
		],
		[
			'slug'    => 'healing-overflow-community-healing',
			'title'   => 'Healing the Community with Fr Paul Abernathy',
			'sdgs'    => [ 'Sustainable Cities and Communities', 'Peace, Justice and Strong Institutions' ],
			'excerpt' => 'Trauma-informed community development and mobile response units.',
			'content' => 'Dr. Toy sits down with Father Paul Abernathy, an Orthodox Christian priest and Iraq War veteran who leads the Neighborhood Resilience Project in Pittsburgh\'s Hill District. Father Paul explains why he witnessed more chronic trauma on local streets than he ever did deployed in a military war zone. He introduces his groundbreaking \'Trauma-Informed Community Development\' framework, operating mobile trauma response RV units on active shooting scenes, and leveraging communal love over traditional clinical models.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Community Action',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Community Action' ],
			'spheres' => [ 'Building Racial Empathy' ],
			'tags'    => [ 'community healing', 'trauma-informed', 'Hill District' ],
			'image'   => 'site/podcasts/healing-overflow-9.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/bMM2yqfItIs',
				'_reci_podcast_duration_label' => '53m',
				'_reci_podcast_duration_secs'  => 3214,
			],
			'post_date'=> '2024-04-08 14:05:20',
		],
		[
			'slug'    => 'healing-overflow-imagination-joy',
			'title'   => 'Breath and Imagination: Joy in times of distress',
			'sdgs'    => [ 'Good Health and Well-being' ],
			'excerpt' => 'Using mindful improv thinking and box breathing to override anxiety.',
			'content' => 'Dr. Toy welcomes back social worker, speaker, and comedy performer Andrea Flack Weatherald. Recording remotely during a Pittsburgh snowstorm, they discuss her \'mindful improv thinking\' framework. Andrea explains how our attention is commoditized by push notifications and media, and outlines how tools like \'Box Breathing,\' EFT Tapping paired with \'Yes, And\' statements, and intentional \'joyful imagination\' can override severe doom-scrolling and internal anxiety.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Cultural Identity',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Cultural Identity' ],
			'spheres' => [ 'Building Racial Empathy' ],
			'tags'    => [ 'imagination', 'joy', 'mindful improv' ],
			'image'   => 'site/podcasts/healing-overflow-10.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/Wk8aVUeH20M',
				'_reci_podcast_duration_label' => '54m',
				'_reci_podcast_duration_secs'  => 3272,
			],
			'post_date'=> '2025-01-12 01:09:20',
		],
		[
			'slug'    => 'healing-overflow-therapist-qa',
			'title'   => 'Ask a Therapist: Questions Answered!',
			'sdgs'    => [ 'Good Health and Well-being' ],
			'excerpt' => 'Understanding how unresolved trauma traps cortisol and adrenaline in the body.',
			'content' => 'In this solo Q&A segment, Dr. Toy addresses two sensitive user-submitted inquiries about deep trauma. She references Bessel van der Kolk\'s The Body Keeps the Score to explain how unresolved trauma traps cortisol and adrenaline in the physical body, generating somatic illnesses like fibromyalgia and chronic pain. Dr. Toy provides an extensive breakdown of therapeutic pathways, including EMDR, trauma-informed yoga, group talk therapy, art/music therapy, interplay movement, and ancestral drumming.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Health Disparities',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Health Disparities', 'Cultural Identity' ],
			'spheres' => [ 'Gauging Racial Inequities' ],
			'tags'    => [ 'trauma', 'EMDR', 'somatic healing' ],
			'image'   => 'site/podcasts/healing-overflow-11.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/fnJzd5MyulM',
				'_reci_podcast_duration_label' => '36m',
				'_reci_podcast_duration_secs'  => 2219,
			],
			'post_date'=> '2026-02-04 07:57:53',
		],
		[
			'slug'    => 'healing-overflow-vaccine-racism',
			'title'   => 'Illuminating the Vaccine for Racism',
			'sdgs'    => [ 'Good Health and Well-being', 'Reduced Inequalities' ],
			'excerpt' => 'Framing systemic racism as a social virus and using SCBT to inoculate against bias.',
			'content' => 'Dr. Toy interviews Ron Idoko, the Associate Director of the Center on Race and Social Problems (CRSP) at the University of Pittsburgh. Ron shares his background as a Bronx-born child of Nigerian immigrants, a former Pitt football player, and his global presentations at the United Nations in Geneva. He introduces his \'Race Equity Consciousness Institute\' (RECI) and frames systemic racism as a social virus, utilizing structured cognitive behavioral training (SCBT) to inoculate against implicit bias.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Systemic Racism',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Systemic Racism', 'Education' ],
			'spheres' => [ 'Recognizing Racial Oppression' ],
			'tags'    => [ 'systemic racism', 'implicit bias', 'RECI' ],
			'image'   => 'site/podcasts/healing-overflow-12.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/KhIoZ7VJpPQ',
				'_reci_podcast_duration_label' => '56m',
				'_reci_podcast_duration_secs'  => 3399,
			],
			'post_date'=> '2024-03-26 22:37:44',
		],
		[
			'slug'    => 'healing-overflow-men-mental-health',
			'title'   => 'Just Heal Bro - Healing Mental Health in Men',
			'sdgs'    => [ 'Good Health and Well-being', 'Gender Equality' ],
			'excerpt' => 'Breaking the stigma and rigid hyper-masculinity that bars men from processing vulnerability.',
			'content' => 'Dr. Toy hosts celebrated television and film actor Lamman Rucker (Greenleaf, Meet the Browns, The Temptations) to discuss black men\'s mental health. Lamman breaks down the stigma, silent suffering, and rigid hyper-masculinity that bars men from processing vulnerability. He details his national work with Dr. Jay Barnett on the \'Just Heal Bro\' tour—advocating for the normalization of therapy, the emotional restructuring of manhood, and innovative clinical concepts like barber shop wellness lounges.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Cultural Identity',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Cultural Identity' ],
			'spheres' => [ 'Embracing Racial Diversity' ],
			'tags'    => [ 'black men', 'mental health', 'vulnerability' ],
			'image'   => 'site/podcasts/healing-overflow-13.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/mv0DM4n9xEY',
				'_reci_podcast_duration_label' => '37m',
				'_reci_podcast_duration_secs'  => 2211,
			],
			'post_date'=> '2026-02-04 10:36:08',
		],
		[
			'slug'    => 'healing-overflow-homicide-grief',
			'title'   => 'Healing after a homicide with Valerie Dixon',
			'sdgs'    => [ 'Peace, Justice and Strong Institutions' ],
			'excerpt' => 'Channeling overwhelming grief into community activism and the PACT Initiative.',
			'content' => 'Dr. Toy welcomes back her close friend, activist, and Center for Victims director Valerie Dixon. Valerie shares the tragic 2001 shooting death of her only son, Robbie, a collegiate football superstar on the cusp of an NFL tryout. Valerie maps out how she channeled her overwhelming grief into launching the PACT Initiative (Prevent Another Crime Today), using unresolved homicide billboard campaigns. She demonstrates the Japanese art of Kintsugi—mending broken pottery with golden glue—as a safe, visual tool to celebrate personal structural scars.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Community Action',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Community Action' ],
			'spheres' => [ 'Acknowledging Racial Trauma' ],
			'tags'    => [ 'grief', 'homicide', 'PACT Initiative' ],
			'image'   => 'site/podcasts/healing-overflow-14.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/g8zd5h4x4CI',
				'_reci_podcast_duration_label' => '36m',
				'_reci_podcast_duration_secs'  => 2165,
			],
			'post_date'=> '2024-04-11 19:36:03',
		],
		[
			'slug'    => 'healing-overflow-repairing-brokenness',
			'title'   => 'Healing Overflow with Dr. Toy - Repairing Brokenness',
			'sdgs'    => [ 'Good Health and Well-being' ],
			'excerpt' => 'The core philosophy of a classroom outside the classroom and the danger of rushing recovery.',
			'content' => 'In this foundational debut episode of her series, Dr. Toy introduces the core philosophy behind her \'classroom outside the classroom\' talk show. Reviewing Sean Glover\'s clinical article How to Recover When Life Crushes You, she warns against rushing out of psychological injuries too quickly. Using the metaphor of a catastrophic car wreck, she urges viewers to give themselves permission to \'stay down\' during acute distress to safely triage emotional blockages instead of forcing a superficial bounce-back.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Cultural Identity',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Cultural Identity', 'Health Disparities' ],
			'spheres' => [ 'Building Racial Empathy' ],
			'tags'    => [ 'healing', 'recovery', 'emotional triage' ],
			'image'   => 'site/podcasts/healing-overflow-15.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/x2dkQlxxE04',
				'_reci_podcast_duration_label' => '17m',
				'_reci_podcast_duration_secs'  => 1041,
			],
			'post_date'=> '2025-10-16 00:33:24',
		],
		[
			'slug'    => 'healing-overflow-find-therapist',
			'title'   => 'How to find a therapist right for you or your loved one!',
			'sdgs'    => [ 'Good Health and Well-being' ],
			'excerpt' => 'A strategic guide on matching mental health needs to proper clinical care.',
			'content' => 'Dr. Toy hosts a strategic, instructional guide on matching personal mental health needs to proper clinical care. She breaks down the technical differences between psychologists (Ph.D./Psy.D. clinicians), psychiatrists (M.D. medication specialists), social workers (LCSW system-oriented providers), and professional counselors (LPCs). She details non-negotiables for identifying cultural alignment, navigating insurance directories, screening waiting lists, and understanding ethical confidentiality barriers.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Technology & Equity',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Health Disparities', 'Technology & Equity' ],
			'spheres' => [ 'Building Racial Empathy' ],
			'tags'    => [ 'therapy', 'mental health care', 'clinical alignment' ],
			'image'   => 'site/podcasts/healing-overflow-16.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/KC_MC6NbeOo',
				'_reci_podcast_duration_label' => '45m',
				'_reci_podcast_duration_secs'  => 2716,
			],
			'post_date'=> '2025-05-13 01:38:10',
		],
		[
			'slug'    => 'healing-overflow-homelessness',
			'title'   => 'Homelessness is our Business!',
			'sdgs'    => [ 'No Poverty', 'Sustainable Cities and Communities' ],
			'excerpt' => 'Debunking myths about the unhoused and discussing structural system voids.',
			'content' => 'Dr. Toy sit downs with Tamiko Dawkins, the Director of Programs at Light of Life Rescue Mission and an Army veteran. Tamiko debunks institutionalized myths regarding the unhoused population, stressing that highly educated corporate professionals like doctors, lawyers, and teachers frequently collapse onto the street due to catastrophic medical co-pays, eviction records, and structural system voids. They discuss encampment outreach strategies, localized safety failures, and the massive data point mapping out high homelessness rates inside the queer/transgender communities.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Community Action',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Community Action', 'Workplace Equity' ],
			'spheres' => [ 'Recognizing Racial Oppression' ],
			'tags'    => [ 'homelessness', 'structural voids', 'queer community' ],
			'image'   => 'site/podcasts/healing-overflow-17.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/ULq9TH_aeRg',
				'_reci_podcast_duration_label' => '42m',
				'_reci_podcast_duration_secs'  => 2543,
			],
			'post_date'=> '2024-02-11 13:09:34',
		],
		[
			'slug'    => 'healing-overflow-anxiety',
			'title'   => 'Anxiety, ugh!',
			'sdgs'    => [ 'Good Health and Well-being' ],
			'excerpt' => 'Diagnosing and treating Generalized Anxiety Disorder and panic attacks.',
			'content' => 'Dr. Toy focuses on diagnosing, normalizing, and treating Generalized Anxiety Disorder (GAD) and severe acute panic attacks. Reviewing criteria out of the DSM-5, she maps out how underlying panic activates primitive fight-or-flight stress responses in the body, generating severe somatic physical pain like constant digestive illnesses and migraines. Using water and a University of Pittsburgh cup as a visual threshold prop, she demonstrates actionable self-regulating habits, including her signature \'Feel Better Bag\' art intervention, muscle progressive relaxation, and tactical cognitive behavioral therapy (CBT).',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Health Disparities',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Health Disparities', 'Cultural Identity' ],
			'spheres' => [ 'Building Racial Empathy' ],
			'tags'    => [ 'anxiety', 'GAD', 'panic attacks', 'CBT' ],
			'image'   => 'site/podcasts/healing-overflow-18.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/4POlX2yD_e4',
				'_reci_podcast_duration_label' => '37m',
				'_reci_podcast_duration_secs'  => 2254,
			],
			'post_date'=> '2025-01-13 20:59:05',
		],
		[
			'slug'    => 'healing-overflow-cps',
			'title'   => 'Helping others to heal through poverty and neglect in the CPS',
			'sdgs'    => [ 'No Poverty', 'Peace, Justice and Strong Institutions' ],
			'excerpt' => 'Breaking down structural disparities inside child welfare and situational poverty.',
			'content' => 'Dr. Toy welcomes Dr. Rachel Armstead (Assistant Administrator of Beaver County Children and Youth Services) to break down structural disparities inside child welfare. Dr. Rachel draws on her 26 years of experience to discuss \'situational\' vs. \'generational\' poverty. She provides actionable, asset-based framing tips for case managers—warning against viewing low-income family behaviors through biased middle-class lenses—and handles an audience question on classroom trauma triggers.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Community Action',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Community Action', 'Systemic Racism' ],
			'spheres' => [ 'Recognizing Racial Oppression' ],
			'tags'    => [ 'CPS', 'child welfare', 'generational poverty' ],
			'image'   => 'site/podcasts/healing-overflow-19.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/cpVxgCCPqRc',
				'_reci_podcast_duration_label' => '46m',
				'_reci_podcast_duration_secs'  => 2820,
			],
			'post_date'=> '2025-11-21 03:49:26',
		],
		[
			'slug'    => 'healing-overflow-imposter-syndrome',
			'title'   => 'Overcoming Imposter Syndrome for Good!',
			'sdgs'    => [ 'Good Health and Well-being', 'Decent Work and Economic Growth' ],
			'excerpt' => 'Distinguishing the true self from the inner imposter voice.',
			'content' => 'Dr. Toy interviews LaQuente \'Coach Q\' Brenson, an ICF-certified executive coach with a background in biology and psychology. Coach Q shares her personal battle with \'imposter experience\' while presenting neurology research at Emory School of Medicine. She outlines how to distinguish your true self from an inner imposter voice, avoid \'emotional hijacking\' by tracking childhood anxieties, reject the hazards of the \'fake it till you make it\' mantra, and show up unapologetically whole in every space.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Workplace Equity',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Workplace Equity', 'Education' ],
			'spheres' => [ 'Embracing Racial Diversity' ],
			'tags'    => [ 'imposter syndrome', 'confidence', 'professional growth' ],
			'image'   => 'site/podcasts/healing-overflow-20.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/DO8g0YB2QGE',
				'_reci_podcast_duration_label' => '48m',
				'_reci_podcast_duration_secs'  => 2881,
			],
			'post_date'=> '2024-09-16 01:02:21',
		],
		[
			'slug'    => 'healing-overflow-art-therapy',
			'title'   => 'Art Therapy and How to Heal Through Creativity',
			'sdgs'    => [ 'Good Health and Well-being' ],
			'excerpt' => 'Exploring neuroesthetics and bilateral guided drawing for anxiety relief.',
			'content' => 'Dr. Toy hosts a \'Dream Team\' panel of art therapists—Megan Cook, Patty Grael, and Angelica Joy Gannon. Angelica breaks down her specialized clinical work at Jewish Family and Community Services helping survivors process trauma following the 2018 Pittsburgh synagogue shooting. They explore neuroesthetics (how the brain\'s pleasure center lights up when experiencing art) and conduct a live, in-studio demonstration of a bilateral \'guided drawing\' somatic exercise to relieve heavy anxiety.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Cultural Identity',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Cultural Identity' ],
			'spheres' => [ 'Building Racial Empathy' ],
			'tags'    => [ 'art therapy', 'neuroesthetics', 'somatic exercise' ],
			'image'   => 'site/podcasts/healing-overflow-21.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/4FhFIUwxwUg',
				'_reci_podcast_duration_label' => '52m',
				'_reci_podcast_duration_secs'  => 3153,
			],
			'post_date'=> '2025-01-06 15:07:12',
		],
		[
			'slug'    => 'healing-overflow-therapist-qa-2',
			'title'   => 'Ask a Therapist Questions are Answered!',
			'sdgs'    => [ 'Good Health and Well-being' ],
			'excerpt' => 'Navigating manipulative family guilt, trauma triggers, and being ghosted.',
			'content' => 'A solo Q&A episode where Dr. Toy fields listener emails. She breaks down the boundaries required to shield against manipulative family guilt-tripping, helps a second-year Pitt student unpack why a classroom lecture on domestic violence triggered a severe \'flight\' response, and provides straight-talk coaching on how to navigate the painful reality of being \'ghosted\' in a toxic relationship.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Cultural Identity',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Health Disparities', 'Cultural Identity' ],
			'spheres' => [ 'Building Racial Empathy' ],
			'tags'    => [ 'boundaries', 'trauma triggers', 'ghosting' ],
			'image'   => 'site/podcasts/healing-overflow-22.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/BFCgS4InEK0',
				'_reci_podcast_duration_label' => '26m',
				'_reci_podcast_duration_secs'  => 1600,
			],
			'post_date'=> '2024-06-13 14:08:36',
		],
		[
			'slug'    => 'healing-overflow-holidays',
			'title'   => 'Happy Holidays?',
			'sdgs'    => [ 'Good Health and Well-being' ],
			'excerpt' => 'Survival tips for protecting mental health during the volatile holiday season.',
			'content' => 'Dr. Toy delivers over 20 survival tips to protect your mental health during the volatile holiday season. She gives practical methods on mapping out escape plans from dysfunctional families, preparing scripts to halt intrusive body-shaming or personal questions, avoiding \'sinking quicksand conversations\' regarding politics, and tips on honorably mourning lost loved ones through shared storytelling.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Cultural Identity',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Cultural Identity' ],
			'spheres' => [ 'Building Racial Empathy' ],
			'tags'    => [ 'holidays', 'family boundaries', 'mental health' ],
			'image'   => 'site/podcasts/healing-overflow-23.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/ZBVC3XPXGD8',
				'_reci_podcast_duration_label' => '34m',
				'_reci_podcast_duration_secs'  => 2058,
			],
			'post_date'=> '2025-10-20 12:56:02',
		],
		[
			'slug'    => 'healing-overflow-sad',
			'title'   => 'Are you SAD? Overcoming Seasonal Affective Disorder',
			'sdgs'    => [ 'Good Health and Well-being' ],
			'excerpt' => 'Navigating the biology of SAD and building pre-emptive immunity.',
			'content' => 'Dr. Toy navigates the clinical criteria, symptoms, and biology of Seasonal Affective Disorder (SAD). She covers the disruption of the body\'s natural circadian rhythm due to dark winter months, how brown eyes absorb light differently, the dangerous traps of self-medicating with alcohol (a natural depressant), and how to build pre-emptive immunity using artificial light boxes, vitamin D, and targeted exercise.',
			'show'    => 'Healing Overflow with Dr Toy',
			'category' => 'Health Disparities',
			'author_name' => 'Dr. Toya Jones',
			'topics'  => [ 'Health Disparities', 'Cultural Identity' ],
			'spheres' => [ 'Gauging Racial Inequities' ],
			'tags'    => [ 'SAD', 'seasonal affective disorder', 'circadian rhythm' ],
			'image'   => 'site/podcasts/healing-overflow-24.webp',
			'meta'    => [
				'_reci_podcast_video_url'      => 'https://youtu.be/VXB8QxW5sdw',
				'_reci_podcast_duration_label' => '18m',
				'_reci_podcast_duration_secs'  => 1120,
			],
			'post_date'=> '2024-08-16 02:50:36',
		],
];
