<?php

return [
	'items' => [
		[
			'kind'     => 'style',
			'slug'     => 'reci-demo-reflection-voices-of-resistance',
			'title'    => 'Voices of Resistance',
			'sdgs'     => [ 'Peace, Justice and Strong Institutions', 'Reduced Inequalities' ],
			'excerpt'  => 'An immersive testimony template — first-person voices remembering the moment they decided enough was enough.',
			'category' => 'Systemic Racism',
			'topics'   => [ 'Community Action', 'Cultural Identity' ],
			'spheres'  => [ 'Building Racial Empathy' ],
			'style'    => 'voices-of-resistance',
			'folder'   => 'voices-of-resistance',
			'featured' => 'pexels-alfomedeiros-11662107.webp',
			'post_date' => '2026-03-10 23:08:06',
			'inner'    => [
				'wikiimages-speech-67628 copy.webp',
				'pexels-zeeshaanshabbir-9746518.webp',
				'pexels-guimaraesm-8547571.webp',
				'pexels-mohammed-abubakr-201794886-19488923.webp',
				'wikiimages-speech-67628.webp',
			],
		],
		[
			'kind'     => 'style',
			'slug'     => 'reci-demo-reflection-breaking-chains',
			'title'    => 'Breaking Chains',
			'sdgs'     => [ 'Peace, Justice and Strong Institutions', 'Reduced Inequalities' ],
			'excerpt'  => 'A parallax journey exploring mass incarceration, systemic justice, and visions for reform.',
			'category' => 'Systemic Racism',
			'topics'   => [ 'Systemic Racism' ],
			'spheres'  => [ 'Recognizing Racial Oppression', 'Building Racial Empathy' ],
			'style'    => 'breaking-chains',
			'folder'   => 'breaking-chains',
			'featured' => 'pexels-charles-awelewa-2147613783-29676620.webp',
			'post_date' => '2024-10-15 23:19:59',
			'inner'    => [ '360_F_696348926_NB7rL1amh93OtY0mHkjLpiMZ6jP0Q6tq.webp', 'pexels-wal_-172619-2156618639-35930741.webp' ],
		],
		[
			'kind'     => 'style',
			'slug'     => 'reci-demo-reflection-march-toward-justice',
			'title'    => 'The March Toward Justice',
			'sdgs'     => [ 'Peace, Justice and Strong Institutions', 'Reduced Inequalities' ],
			'excerpt'  => 'A documentary-march template tracing the 1965 fight for the ballot — step by step toward the soul of democracy.',
			'category' => 'Systemic Racism',
			'topics'   => [ 'Community Action' ],
			'spheres'  => [ 'Recognizing Racial Oppression', 'Building Racial Empathy' ],
			'style'    => 'march-toward-justice',
			'folder'   => 'march-towards-justice',
			'featured' => 'Dr-Martin-Luther-King-Jr-in-the-midst-at-the-March-on-Washington.webp',
			'post_date' => '2026-03-03 22:07:19',
			'inner'    => [ 'Civil-Rights-Leaders-in-Selma-600x428.webp', 'GettyImages-525580854-1.webp', 'images.webp', 'pexels-airamdphoto-9751037.webp' ],
		],
		[
			'kind'     => 'style',
			'slug'     => 'reci-demo-reflection-racial-disparities',
			'title'    => 'Racial Disparities',
			'sdgs'     => [ 'Good Health and Well-being', 'Reduced Inequalities' ],
			'excerpt'  => 'An analytical template that turns the data of inequity into an interactive, card-based exploration.',
			'category' => 'Systemic Racism',
			'topics'   => [ 'Health Disparities', 'Systemic Racism' ],
			'spheres'  => [ 'Gauging Racial Inequities' ],
			'style'    => 'racial-disparities',
			'folder'   => 'racial-disparities',
			'featured' => 'pexels-anna-nekrashevich-8058540.webp',
			'post_date' => '2024-02-04 19:14:43',
			'inner'    => [ 'Diversity_2-1024x844.webp' ],
		],
		[
			'kind'     => 'black-wall',
			'slug'     => 'reci-demo-black-wall-street',
			'title'    => 'Black Wall Street',
			'sdgs'     => [ 'Decent Work and Economic Growth', 'Reduced Inequalities' ],
			'excerpt'  => 'An immersive reflection on Greenwood: its rise, the 1921 Tulsa Race Massacre, the cover-up, and the rebuilding.',
			'category' => 'Systemic Racism',
			'topics'   => [ 'Community Action', 'Systemic Racism' ],
			'spheres'  => [ 'Recognizing Racial Oppression', 'Building Racial Empathy' ],
			'featured' => 'site/reflections/black-wall/main.webp',
			'post_date' => '2025-12-11 17:56:57',
			'assets'   => [
				'site/reflections/black-wall/main.webp',
				'site/reflections/black-wall/Blackwall-street.webp',
				'site/reflections/black-wall/bws-07.webp',
				'site/reflections/black-wall/bws-08.webp',
				'site/reflections/black-wall/bws-09.webp',
				'site/reflections/black-wall/bws-12.webp',
				'site/reflections/black-wall/bws-13.webp',
				'site/reflections/black-wall/bws-14.webp',
				'site/reflections/black-wall/bws-15.webp',
				'site/reflections/black-wall/bws-16.webp',
				'site/reflections/black-wall/bws-18.webp',
				'site/reflections/black-wall/bws-19.webp',
			],
		],
		[
			'kind'     => 'we-humans',
			'slug'     => 'reci-demo-we-humans',
			'title'    => '"We Humans": Educating Pittsburgh on Race in the 1950s',
			'sdgs'     => [ 'Quality Education', 'Reduced Inequalities' ],
			'excerpt'  => 'A digital exhibit on the 1955 Carnegie Museum "We Humans" exhibit — how Pittsburgh civic, labor, and education leaders taught about race in the 1950s, and what its ambitions and shortcomings teach us now.',
			'category' => 'Systemic Racism',
			'topics'   => [ 'Education', 'Systemic Racism' ],
			'spheres'  => [ 'Recognizing Racial Oppression', 'Building Racial Empathy' ],
			'featured' => 'site/reflections/we-humans/students-1959.webp',
			'post_date' => '2025-01-28 19:49:11',
			'assets'   => [
				'site/reflections/we-humans/students-1959.webp',
				'site/reflections/we-humans/are-you-ethnocentric.webp',
				'site/reflections/we-humans/ethnocentric.webp',
				'site/reflections/we-humans/teacher-1959.webp',
				'site/reflections/we-humans/courier-1956.webp',
				'site/reflections/we-humans/sf-library-1959.webp',
				'site/reflections/we-humans/indianapolis-1.webp',
				'site/reflections/we-humans/indianapolis-2.webp',
				'site/reflections/we-humans/panel-1a.webp',
				'site/reflections/we-humans/panel-1b.webp',
				'site/reflections/we-humans/panel-2a.webp',
				'site/reflections/we-humans/panel-2b.webp',
				'site/reflections/we-humans/panel-3a.webp',
				'site/reflections/we-humans/panel-3b.webp',
				'site/reflections/we-humans/panel-4a.webp',
				'site/reflections/we-humans/panel-4b.webp',
				'site/reflections/we-humans/about.webp',
			],
		],
	],
];
