<?php

return [
	[
		'slug'    => 'reci-video-trailer-illuminating-vaccine-racism',
		'title'   => 'Illuminating the Vaccine for Racism - Trailer',
		'sdgs'    => [ 'Good Health and Well-being', 'Reduced Inequalities' ],
		'excerpt' => 'Watch the trailer for Illuminating the Vaccine for Racism, an engaging film about public health and equity.',
		'content' => reci_demo_lorem( 2 ),
        'spheres' => [ 'Recognizing Racial Oppression' ],
        'tags'    => [ 'Public Health', 'Systemic Racism' ],
		'topics'  => [ 'Health Disparities', 'Systemic Racism' ],
		'image'   => 'site/videos/yt_video_1.webp',
		'post_date' => '2025-05-31 12:24:41',
			'meta'    => [
			'_reci_video_url'      => 'https://www.youtube.com/watch?v=HICAe_b4wYY',
			'_reci_video_duration' => '2:30', // Estimated
		],
	],
	[
		'slug'    => 'reci-video-human-flourishing-symposium',
		'title'   => 'Human Flourishing Symposium',
		'sdgs'    => [ 'Good Health and Well-being', 'Quality Education' ],
		'excerpt' => 'The Human Flourishing Research Collaborative at the University of Pittsburgh recently hosted the Human Flourishing Symposium, bringing together students, faculty and the community.',
		'content' => reci_demo_lorem( 2 ),
        'spheres' => [ 'Acknowledging Racial Trauma and Fostering Racial Healing' ],
        'tags'    => [ 'Human Flourishing', 'Community Action' ],
		'topics'  => [ 'Community Action' ],
		'image'   => 'site/videos/yt_video_2.webp',
		'post_date' => '2025-10-30 16:44:19',
			'meta'    => [
			'_reci_video_url'      => 'https://www.youtube.com/watch?v=dS1yTJ2D1VQ',
			'_reci_video_duration' => '5:48',
		],
	],
	[
		'slug'    => 'reci-video-national-day-racial-healing',
		'title'   => 'National Day of Racial Healing - CRSP',
		'sdgs'    => [ 'Peace, Justice and Strong Institutions', 'Reduced Inequalities' ],
		'excerpt' => 'The Center on Race and Social Problems (CRSP) held a special program in honor of the National Day of Racial Healing in January. Our theme for this program was building community.',
		'content' => reci_demo_lorem( 2 ),
        'spheres' => [ 'Acknowledging Racial Trauma and Fostering Racial Healing' ],
        'tags'    => [ 'Racial Healing', 'Community Action' ],
		'topics'  => [ 'Cultural Identity', 'Community Action' ],
		'image'   => 'site/videos/yt_video_3.webp',
		'post_date' => '2025-09-06 22:03:47',
			'meta'    => [
			'_reci_video_url'      => 'https://www.youtube.com/watch?v=n_YvIayYxdg',
			'_reci_video_duration' => '3:20',
		],
	],
	[
		'slug'    => 'reci-video-building-beloved-community',
		'title'   => 'Building Beloved Community - A Peacebuilding and Nonviolence Workshop',
		'sdgs'    => [ 'Peace, Justice and Strong Institutions', 'Sustainable Cities and Communities' ],
		'excerpt' => 'Pitt\'s Center on Race and Social Problems and Frederick Honors College in collaboration with the Alliance for Humanitarian Initiatives, Nonviolence, and Spiritual peacebuilding.',
		'content' => reci_demo_lorem( 2 ),
        'spheres' => [ 'Building Racial Empathy' ],
        'tags'    => [ 'Peacebuilding', 'Community Action' ],
		'topics'  => [ 'Community Action' ],
		'image'   => 'site/videos/yt_video_4.webp',
		'post_date' => '2026-05-15 13:08:49',
			'meta'    => [
			'_reci_video_url'      => 'https://www.youtube.com/watch?v=wf96HD66BGE',
			'_reci_video_duration' => '3:54',
		],
	],
	[
		'slug'    => 'reci-video-film-premiere-illuminating',
		'title'   => 'RECI Film Premiere: \'Illuminating the Vaccine for Racism\'',
		'sdgs'    => [ 'Good Health and Well-being', 'Reduced Inequalities' ],
		'excerpt' => 'On January 25th, Pittsburgh community members attended the RECI Film Premiere, featuring a screening of \'Illuminating the Vaccine for Racism,\' an engaging panel discussion.',
		'content' => reci_demo_lorem( 2 ),
        'spheres' => [ 'Embracing Racial Diversity' ],
        'tags'    => [ 'Public Health', 'Cultural Identity' ],
		'topics'  => [ 'Health Disparities', 'Cultural Identity' ],
		'image'   => 'site/videos/yt_video_5.webp',
		'post_date' => '2025-10-29 10:21:25',
			'meta'    => [
			'_reci_video_url'      => 'https://www.youtube.com/watch?v=7pLxr1YcAJ8',
			'_reci_video_duration' => '2:39',
		],
	],
	[
		'slug'    => 'reci-video-national-day-racial-healing-2026',
		'title'   => 'National Day of Racial Healing 2026 - Dr. Kyaien Conner\'s Opening Remarks',
		'sdgs'    => [ 'Peace, Justice and Strong Institutions', 'Reduced Inequalities' ],
		'excerpt' => 'Opening Remarks by Dr. Kyaien Conner for the National Day of Racial Healing.',
		'content' => reci_demo_lorem( 2 ),
        'spheres' => [ 'Integrating Racial Equity and Navigating Racial Conflict' ],
        'tags'    => [ 'Racial Healing', 'Leadership' ],
		'topics'  => [ 'Cultural Identity', 'Workplace Equity' ],
		'image'   => 'site/videos/yt_video_6.webp',
		'post_date' => '2026-02-24 04:34:46',
			'meta'    => [
			'_reci_video_url'      => 'https://youtu.be/984JpOrzHCw?si=iOI4Ijm3MGi6zVNo',
			'_reci_video_duration' => '4:15', // Estimated
		],
	],
];
